[package]
name = "serial_tool"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = { version = "0.4.38", default-features = false, features = ["clock", "std"] }
serialport = "4.7.0"

[target.'cfg(target_os = "linux")'.dependencies]
eframe = { version = "0.31.1", default-features = false, features = ["default_fonts", "glow", "wayland", "x11"] }

[target.'cfg(not(target_os = "linux"))'.dependencies]
eframe = { version = "0.31.1", default-features = false, features = ["default_fonts", "glow"] }

[profile.release]
codegen-units = 1
lto = "thin"
opt-level = 3
strip = true
